FROM node:20

WORKDIR /app

RUN npm install -g pnpm@9.0.0

COPY package.json pnpm-lock.yaml* ./
COPY pnpm-workspace.yaml ./
COPY turbo.json ./
COPY packages ./packages
COPY apps/api ./apps/api

RUN pnpm install
RUN pnpm db:generate
RUN pnpm build --filter=api

EXPOSE 4000

CMD ["node", "apps/api/dist/main.js"]
