# syntax=docker/dockerfile:1
# -------------------------------------
# STAGE 1: Prune (Extraer app y dependencias)
# -------------------------------------
FROM node:20-alpine AS builder
RUN apk add --no-cache libc6-compat
RUN npm install -g pnpm turbo

WORKDIR /app
COPY . .
# Extrae solo lo necesario para compilar 'web'
RUN turbo prune web --docker

# -------------------------------------
# STAGE 2: Install & Build
# -------------------------------------
FROM node:20-alpine AS installer
RUN apk add --no-cache libc6-compat
RUN npm install -g pnpm turbo

WORKDIR /app

COPY .gitignore .gitignore
COPY --from=builder /app/out/json/ .
COPY --from=builder /app/out/pnpm-lock.yaml ./pnpm-lock.yaml

RUN pnpm install

COPY --from=builder /app/out/full/ .

# El cliente prisma puede ser requerido si Next.js accede a la bd directa
RUN npx prisma generate --schema=./packages/database/prisma/schema.prisma || true

# Next.js telemetry disable
ENV NEXT_TELEMETRY_DISABLED 1

# Compilar Next.js (Nota: Asegurarse de tener 'output: "standalone"' en next.config.mjs)
RUN turbo run build --filter=web...

# -------------------------------------
# STAGE 3: Runner (Producción)
# -------------------------------------
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs
USER nextjs

COPY --from=installer /app/apps/web/next.config.mjs .
COPY --from=installer /app/apps/web/package.json .

# Copiar estáticos y el empaquetado standalone
COPY --from=installer --chown=nextjs:nodejs /app/apps/web/.next/standalone ./
COPY --from=installer --chown=nextjs:nodejs /app/apps/web/.next/static ./apps/web/.next/static
COPY --from=installer --chown=nextjs:nodejs /app/apps/web/public ./apps/web/public

EXPOSE 3000

ENV PORT 3000
# El archivo server.js es generado por el modo standalone en Next.js
CMD ["node", "apps/web/server.js"]
