export interface KpiDefinitionEntry {
  code: string
  categoryCode: string
  categoryName: string
  indicatorClass: string
  name: string
  formula: string
  unit: string
  direction: 'up' | 'down'
  targetValue: number
  minValue: number
  maxValue: number
}

export const KPI_DEFINITIONS: KpiDefinitionEntry[] = [
  {
    code: 'NOR_DIS_IND_01',
    categoryCode: 'PURCHASING',
    categoryName: 'Compras y Abastecimiento',
    indicatorClass: 'PERFORMANCE',
    name: 'Certificación de Proveedores',
    formula: '(Proveedores Certificados / Total Proveedores) * 100',
    unit: '%',
    direction: 'up',
    targetValue: 85,
    minValue: 0,
    maxValue: 100,
  },
  {
    code: 'NOR_DIS_IND_02',
    categoryCode: 'PURCHASING',
    categoryName: 'Compras y Abastecimiento',
    indicatorClass: 'PERFORMANCE',
    name: 'Calidad de los Pedidos Generados',
    formula: '(Pedidos sin problemas / Total Pedidos) * 100',
    unit: '%',
    direction: 'up',
    targetValue: 95,
    minValue: 0,
    maxValue: 100,
  },
  {
    code: 'NOR_DIS_IND_03',
    categoryCode: 'PURCHASING',
    categoryName: 'Compras y Abastecimiento',
    indicatorClass: 'PERFORMANCE',
    name: 'Entregas Perfectamente Recibidas',
    formula: '(Pedidos Rechazados / Total Pedidos Recibidos) * 100',
    unit: '%',
    direction: 'down',
    targetValue: 5,
    minValue: 0,
    maxValue: 100,
  },
  {
    code: 'NOR_DIS_IND_04',
    categoryCode: 'PURCHASING',
    categoryName: 'Compras y Abastecimiento',
    indicatorClass: 'PRODUCTIVITY',
    name: 'Volumen de Compra',
    formula: '(Valor Compras / Valor Ventas Totales) * 100',
    unit: '%',
    direction: 'down',
    targetValue: 60,
    minValue: 0,
    maxValue: 100,
  },
  {
    code: 'NOR_DIS_IND_05',
    categoryCode: 'INVENTORY',
    categoryName: 'Inventarios y Producción',
    indicatorClass: 'UTILIZATION',
    name: 'Capacidad de Producción Utilizada',
    formula: '(Capacidad Utilizada / Capacidad Disponible) * 100',
    unit: '%',
    direction: 'up',
    targetValue: 80,
    minValue: 0,
    maxValue: 100,
  },
  {
    code: 'NOR_DIS_IND_06',
    categoryCode: 'INVENTORY',
    categoryName: 'Inventarios y Producción',
    indicatorClass: 'PERFORMANCE',
    name: 'Rendimiento de Máquinas',
    formula: '(Producción Real / Capacidad Estándar) * 100',
    unit: '%',
    direction: 'up',
    targetValue: 90,
    minValue: 0,
    maxValue: 100,
  },
  {
    code: 'NOR_DIS_IND_07',
    categoryCode: 'INVENTORY',
    categoryName: 'Inventarios y Producción',
    indicatorClass: 'PERFORMANCE',
    name: 'Nivel de Cumplimiento de Despacho',
    formula: '(Pedidos Despachados / Pedidos Solicitados) * 100',
    unit: '%',
    direction: 'up',
    targetValue: 95,
    minValue: 0,
    maxValue: 100,
  },
  {
    code: 'NOR_DIS_IND_08',
    categoryCode: 'INVENTORY',
    categoryName: 'Inventarios y Producción',
    indicatorClass: 'PRODUCTIVITY',
    name: 'Rotación de Mercancía',
    formula: 'Ventas Acumuladas / Inventario Promedio',
    unit: 'veces',
    direction: 'up',
    targetValue: 6,
    minValue: 0,
    maxValue: 24,
  },
  {
    code: 'NOR_DIS_IND_09',
    categoryCode: 'INVENTORY',
    categoryName: 'Inventarios y Producción',
    indicatorClass: 'PRODUCTIVITY',
    name: 'Duración del Inventario',
    formula: '(Inventario Final / Ventas Promedio) * 30 días',
    unit: 'días',
    direction: 'down',
    targetValue: 30,
    minValue: 0,
    maxValue: 120,
  },
  {
    code: 'NOR_DIS_IND_10',
    categoryCode: 'INVENTORY',
    categoryName: 'Inventarios y Producción',
    indicatorClass: 'PERFORMANCE',
    name: 'Vejez del Inventario',
    formula: '(Unidades obsoletas / Total Unidades) * 100',
    unit: '%',
    direction: 'down',
    targetValue: 5,
    minValue: 0,
    maxValue: 100,
  },
  {
    code: 'NOR_DIS_IND_11',
    categoryCode: 'INVENTORY',
    categoryName: 'Inventarios y Producción',
    indicatorClass: 'PERFORMANCE',
    name: 'Exactitud del Inventario',
    formula: '(Valor Diferencia / Valor Inventario Físico) * 100',
    unit: '%',
    direction: 'down',
    targetValue: 2,
    minValue: 0,
    maxValue: 100,
  },
  {
    code: 'NOR_DIS_IND_12',
    categoryCode: 'WAREHOUSING',
    categoryName: 'Almacenamiento y Bodegaje',
    indicatorClass: 'PRODUCTIVITY',
    name: 'Costo de Almacenamiento por Unidad',
    formula: 'Costo Bodegaje / Unidades Almacenadas',
    unit: '$/und',
    direction: 'down',
    targetValue: 0,
    minValue: 0,
    maxValue: 100000,
  },
  {
    code: 'NOR_DIS_IND_13',
    categoryCode: 'WAREHOUSING',
    categoryName: 'Almacenamiento y Bodegaje',
    indicatorClass: 'PRODUCTIVITY',
    name: 'Costo por Metro Cuadrado',
    formula: 'Costo Total Bodega / Área Total Utilizable',
    unit: '$/m²',
    direction: 'down',
    targetValue: 0,
    minValue: 0,
    maxValue: 500000,
  },
  {
    code: 'NOR_DIS_IND_14',
    categoryCode: 'WAREHOUSING',
    categoryName: 'Almacenamiento y Bodegaje',
    indicatorClass: 'PRODUCTIVITY',
    name: 'Unidades Despachadas por Empleado',
    formula: 'Unidades Despachadas / Total Empleados Bodega',
    unit: 'und/emp',
    direction: 'up',
    targetValue: 1000,
    minValue: 0,
    maxValue: 10000,
  },
  {
    code: 'NOR_DIS_IND_15',
    categoryCode: 'WAREHOUSING',
    categoryName: 'Almacenamiento y Bodegaje',
    indicatorClass: 'PRODUCTIVITY',
    name: 'Costo de Despacho por Empleado',
    formula: 'Costo Operativo Bodega / Total Empleados Bodega',
    unit: '$/emp',
    direction: 'down',
    targetValue: 0,
    minValue: 0,
    maxValue: 5000000,
  },
  {
    code: 'NOR_DIS_IND_16',
    categoryCode: 'WAREHOUSING',
    categoryName: 'Almacenamiento y Bodegaje',
    indicatorClass: 'PERFORMANCE',
    name: 'Nivel de Cumplimiento en Despacho',
    formula: '(Pedidos Despachados a Tiempo / Total Pedidos) * 100',
    unit: '%',
    direction: 'up',
    targetValue: 95,
    minValue: 0,
    maxValue: 100,
  },
  {
    code: 'NOR_DIS_IND_17',
    categoryCode: 'WAREHOUSING',
    categoryName: 'Almacenamiento y Bodegaje',
    indicatorClass: 'PRODUCTIVITY',
    name: 'Costo por Unidad Despachada',
    formula: 'Costo Operativo Bodega / Unidades Despachadas',
    unit: '$/und',
    direction: 'down',
    targetValue: 0,
    minValue: 0,
    maxValue: 50000,
  },
  {
    code: 'NOR_DIS_IND_18',
    categoryCode: 'TRANSPORT',
    categoryName: 'Transporte y Distribución',
    indicatorClass: 'PRODUCTIVITY',
    name: 'Costo de Transporte vs Ventas',
    formula: '(Costo Transporte / Ventas Totales) * 100',
    unit: '%',
    direction: 'down',
    targetValue: 8,
    minValue: 0,
    maxValue: 100,
  },
  {
    code: 'NOR_DIS_IND_19',
    categoryCode: 'TRANSPORT',
    categoryName: 'Transporte y Distribución',
    indicatorClass: 'PRODUCTIVITY',
    name: 'Costo Operativo por Conductor',
    formula: 'Costo Transporte / Número Conductores',
    unit: '$/cond',
    direction: 'down',
    targetValue: 0,
    minValue: 0,
    maxValue: 10000000,
  },
  {
    code: 'NOR_DIS_IND_20',
    categoryCode: 'TRANSPORT',
    categoryName: 'Transporte y Distribución',
    indicatorClass: 'PERFORMANCE',
    name: 'Comparativo de Transporte (Propio vs 3PL)',
    formula: 'Costo Propio por Unidad / Costo 3PL por Unidad',
    unit: 'ratio',
    direction: 'down',
    targetValue: 1,
    minValue: 0,
    maxValue: 5,
  },
  {
    code: 'NOR_DIS_IND_21',
    categoryCode: 'CUSTOMER_SERVICE',
    categoryName: 'Servicio al Cliente',
    indicatorClass: 'PERFORMANCE',
    name: 'Entregas Recibidas a Tiempo',
    formula: '(Pedidos Entregados a Tiempo / Total Pedidos) * 100',
    unit: '%',
    direction: 'up',
    targetValue: 95,
    minValue: 0,
    maxValue: 100,
  },
  {
    code: 'NOR_DIS_IND_22',
    categoryCode: 'CUSTOMER_SERVICE',
    categoryName: 'Servicio al Cliente',
    indicatorClass: 'PERFORMANCE',
    name: 'Entregas Completas',
    formula: '(Pedidos Completos / Total Pedidos) * 100',
    unit: '%',
    direction: 'up',
    targetValue: 95,
    minValue: 0,
    maxValue: 100,
  },
  {
    code: 'NOR_DIS_IND_23',
    categoryCode: 'CUSTOMER_SERVICE',
    categoryName: 'Servicio al Cliente',
    indicatorClass: 'PERFORMANCE',
    name: 'Calidad de la Documentación',
    formula: '(Facturas sin Errores / Total Facturas Generadas) * 100',
    unit: '%',
    direction: 'up',
    targetValue: 98,
    minValue: 0,
    maxValue: 100,
  },
  {
    code: 'NOR_DIS_IND_24',
    categoryCode: 'CUSTOMER_SERVICE',
    categoryName: 'Servicio al Cliente',
    indicatorClass: 'PERFORMANCE',
    name: 'Entregas Perfectas',
    formula: 'Entregas a Tiempo * Entregas Completas * Doc. OK',
    unit: '%',
    direction: 'up',
    targetValue: 90,
    minValue: 0,
    maxValue: 100,
  },
  {
    code: 'NOR_DIS_IND_25',
    categoryCode: 'CUSTOMER_SERVICE',
    categoryName: 'Servicio al Cliente',
    indicatorClass: 'PRODUCTIVITY',
    name: 'Costo Logístico vs Ventas',
    formula: '(Costos Logísticos Totales / Ventas Totales) * 100',
    unit: '%',
    direction: 'down',
    targetValue: 12,
    minValue: 0,
    maxValue: 100,
  },
  {
    code: 'NOR_DIS_IND_26',
    categoryCode: 'CUSTOMER_SERVICE',
    categoryName: 'Servicio al Cliente',
    indicatorClass: 'PRODUCTIVITY',
    name: 'Costo Logístico vs Utilidad Bruta',
    formula: '(Costos Logísticos Totales / Utilidad Bruta) * 100',
    unit: '%',
    direction: 'down',
    targetValue: 20,
    minValue: 0,
    maxValue: 100,
  },
  {
    code: 'NOR_DIS_IND_27',
    categoryCode: 'CUSTOMER_SERVICE',
    categoryName: 'Servicio al Cliente',
    indicatorClass: 'PRODUCTIVITY',
    name: 'Costo de CEDI vs Ventas',
    formula: '(Costo Operativo CEDI / Ventas Totales) * 100',
    unit: '%',
    direction: 'down',
    targetValue: 5,
    minValue: 0,
    maxValue: 100,
  },
  {
    code: 'NOR_DIS_IND_28',
    categoryCode: 'INTERNATIONAL_TRADE',
    categoryName: 'Importaciones y Exportaciones',
    indicatorClass: 'PRODUCTIVITY',
    name: 'Costo Unitario de Importación/Exportación',
    formula: 'Costo Total Operación / Unidades Importadas/Exportadas',
    unit: '$USD/und',
    direction: 'down',
    targetValue: 0,
    minValue: 0,
    maxValue: 10000,
  },
]

export const KPI_CATEGORIES = [
  { code: 'PURCHASING', name: 'Compras y Abastecimiento', color: '#3b82f6', displayOrder: 1 },
  { code: 'INVENTORY', name: 'Inventarios y Producción', color: '#10b981', displayOrder: 2 },
  { code: 'WAREHOUSING', name: 'Almacenamiento y Bodegaje', color: '#f59e0b', displayOrder: 3 },
  { code: 'TRANSPORT', name: 'Transporte y Distribución', color: '#8b5cf6', displayOrder: 4 },
  { code: 'CUSTOMER_SERVICE', name: 'Servicio al Cliente', color: '#ec4899', displayOrder: 5 },
  { code: 'INTERNATIONAL_TRADE', name: 'Importaciones y Exportaciones', color: '#06b6d4', displayOrder: 6 },
]

export function getKpiByCode(code: string): KpiDefinitionEntry | undefined {
  return KPI_DEFINITIONS.find(k => k.code === code)
}

export function getKpisByCategory(categoryCode: string): KpiDefinitionEntry[] {
  return KPI_DEFINITIONS.filter(k => k.categoryCode === categoryCode)
}
