/**
 * Catálogo de 28 KPIs logísticos — Capítulos 3.1 a 3.6
 * chartType se almacena en dataSource como prefijo "chart:<tipo>"
 */
export type ChartType = 'line' | 'bar' | 'composed' | 'barHorizontal';

export interface KpiSeedDefinition {
  code: string;
  categoryCode: string;
  name: string;
  description: string;
  formula: string;
  unit: string;
  unitType: 'percentage' | 'currency' | 'days' | 'ratio' | 'units';
  indicatorClass: 'UTILIZATION' | 'PERFORMANCE' | 'PRODUCTIVITY';
  direction: 'up' | 'down';
  targetValue: number;
  responsibleRole: string;
  chartType: ChartType;
  displayOrder: number;
}

export const KPI_CATEGORIES = [
  {
    code: 'CAT_3_1',
    name: 'Compras y abastecimiento',
    description: 'Indicadores de gestión de compras y proveedores (Cap. 3.1)',
    icon: 'ShoppingCart',
    color: '#2563eb',
    displayOrder: 1,
  },
  {
    code: 'CAT_3_2',
    name: 'Producción e inventarios',
    description: 'Capacidad, rendimiento y gestión de inventarios (Cap. 3.2)',
    icon: 'Factory',
    color: '#7c3aed',
    displayOrder: 2,
  },
  {
    code: 'CAT_3_3',
    name: 'Almacenamiento',
    description: 'Costos y productividad del CEDI / almacén (Cap. 3.3)',
    icon: 'Package',
    color: '#059669',
    displayOrder: 3,
  },
  {
    code: 'CAT_3_4',
    name: 'Transporte',
    description: 'Eficiencia y costos de transporte (Cap. 3.4)',
    icon: 'Truck',
    color: '#d97706',
    displayOrder: 4,
  },
  {
    code: 'CAT_3_5',
    name: 'Servicio al cliente',
    description: 'Calidad de entrega y costos logísticos vs ventas (Cap. 3.5)',
    icon: 'Users',
    color: '#dc2626',
    displayOrder: 5,
  },
  {
    code: 'CAT_3_6',
    name: 'Importaciones',
    description: 'Comercio exterior (Cap. 3.6)',
    icon: 'Globe',
    color: '#0891b2',
    displayOrder: 6,
  },
] as const;

export const KPI_DEFINITIONS: KpiSeedDefinition[] = [
  // 3.1 Compras
  {
    code: 'NOR_DIS_IND_01',
    categoryCode: 'CAT_3_1',
    name: 'Certificación de proveedores',
    description: 'Porcentaje de proveedores certificados sobre el total activo.',
    formula: '(Proveedores certificados / Total proveedores activos) × 100',
    unit: '%',
    unitType: 'percentage',
    indicatorClass: 'PERFORMANCE',
    direction: 'up',
    targetValue: 90,
    responsibleRole: 'PURCHASING_MANAGER',
    chartType: 'bar',
    displayOrder: 1,
  },
  {
    code: 'NOR_DIS_IND_02',
    categoryCode: 'CAT_3_1',
    name: 'Calidad de pedidos generados',
    description: 'Pedidos sin errores sobre el total de pedidos generados.',
    formula: '(Pedidos sin error / Total pedidos generados) × 100',
    unit: '%',
    unitType: 'percentage',
    indicatorClass: 'PERFORMANCE',
    direction: 'up',
    targetValue: 95,
    responsibleRole: 'PURCHASING_MANAGER',
    chartType: 'line',
    displayOrder: 2,
  },
  {
    code: 'NOR_DIS_IND_03',
    categoryCode: 'CAT_3_1',
    name: 'Volumen de compra',
    description: 'Volumen o valor total de compras en el periodo.',
    formula: 'Σ Valor neto de órdenes de compra aprobadas en el periodo',
    unit: 'COP',
    unitType: 'currency',
    indicatorClass: 'PRODUCTIVITY',
    direction: 'up',
    targetValue: 50000000,
    responsibleRole: 'PURCHASING_MANAGER',
    chartType: 'bar',
    displayOrder: 3,
  },
  {
    code: 'NOR_DIS_IND_04',
    categoryCode: 'CAT_3_1',
    name: 'Entregas perfectamente recibidas',
    description: 'Recepciones sin novedad sobre total de recepciones.',
    formula: '(Entregas perfectas recibidas / Total entregas recibidas) × 100',
    unit: '%',
    unitType: 'percentage',
    indicatorClass: 'PERFORMANCE',
    direction: 'up',
    targetValue: 95,
    responsibleRole: 'PURCHASING_MANAGER',
    chartType: 'line',
    displayOrder: 4,
  },
  // 3.2 Producción e inventarios
  {
    code: 'NOR_DIS_IND_26',
    categoryCode: 'CAT_3_2',
    name: 'Capacidad de producción utilizada',
    description: 'Utilización de la capacidad instalada.',
    formula: '(Producción real / Capacidad máxima) × 100',
    unit: '%',
    unitType: 'percentage',
    indicatorClass: 'UTILIZATION',
    direction: 'up',
    targetValue: 85,
    responsibleRole: 'OPERATIONS_MANAGER',
    chartType: 'barHorizontal',
    displayOrder: 1,
  },
  {
    code: 'NOR_DIS_IND_27',
    categoryCode: 'CAT_3_2',
    name: 'Rendimiento de máquina',
    description: 'Eficiencia de equipos de producción.',
    formula: '(Unidades producidas / Capacidad máxima) × 100',
    unit: '%',
    unitType: 'percentage',
    indicatorClass: 'PERFORMANCE',
    direction: 'up',
    targetValue: 88,
    responsibleRole: 'OPERATIONS_MANAGER',
    chartType: 'composed',
    displayOrder: 2,
  },
  {
    code: 'NOR_DIS_IND_05',
    categoryCode: 'CAT_3_2',
    name: 'Rotación de mercancía',
    description: 'Velocidad de rotación del inventario.',
    formula: 'Ventas del periodo / Inventario promedio',
    unit: 'veces',
    unitType: 'ratio',
    indicatorClass: 'PRODUCTIVITY',
    direction: 'up',
    targetValue: 6,
    responsibleRole: 'OPERATIONS_MANAGER',
    chartType: 'line',
    displayOrder: 3,
  },
  {
    code: 'NOR_DIS_IND_06',
    categoryCode: 'CAT_3_2',
    name: 'Duración del inventario',
    description: 'Días de cobertura del inventario.',
    formula: '(Inventario final / Ventas promedio diarias) × 30',
    unit: 'días',
    unitType: 'days',
    indicatorClass: 'PERFORMANCE',
    direction: 'down',
    targetValue: 45,
    responsibleRole: 'OPERATIONS_MANAGER',
    chartType: 'line',
    displayOrder: 4,
  },
  {
    code: 'NOR_DIS_IND_07',
    categoryCode: 'CAT_3_2',
    name: 'Vejez del inventario',
    description: 'Proporción de inventario dañado, obsoleto o vencido.',
    formula: '((Dañadas + Obsoletas + Vencidas) / Disponibles) × 100',
    unit: '%',
    unitType: 'percentage',
    indicatorClass: 'PERFORMANCE',
    direction: 'down',
    targetValue: 3,
    responsibleRole: 'OPERATIONS_MANAGER',
    chartType: 'bar',
    displayOrder: 5,
  },
  {
    code: 'NOR_DIS_IND_08',
    categoryCode: 'CAT_3_2',
    name: 'Valor económico del inventario',
    description: 'Valor monetario del inventario disponible.',
    formula: 'Σ (Cantidad disponible × Costo unitario)',
    unit: 'COP',
    unitType: 'currency',
    indicatorClass: 'PRODUCTIVITY',
    direction: 'down',
    targetValue: 50000000,
    responsibleRole: 'OPERATIONS_MANAGER',
    chartType: 'bar',
    displayOrder: 6,
  },
  {
    code: 'NOR_DIS_IND_09',
    categoryCode: 'CAT_3_2',
    name: 'Exactitud de inventarios',
    description: 'Precisión del inventario físico vs sistema.',
    formula: '(Unidades contadas correctas / Total unidades contadas) × 100',
    unit: '%',
    unitType: 'percentage',
    indicatorClass: 'PERFORMANCE',
    direction: 'up',
    targetValue: 98,
    responsibleRole: 'OPERATIONS_MANAGER',
    chartType: 'line',
    displayOrder: 7,
  },
  // 3.3 Almacenamiento
  {
    code: 'NOR_DIS_IND_10',
    categoryCode: 'CAT_3_3',
    name: 'Costo por unidad almacenada',
    formula: 'Costos totales de almacenamiento / Unidades almacenadas',
    description: 'Costo promedio por unidad almacenada en el periodo.',
    unit: 'COP',
    unitType: 'currency',
    indicatorClass: 'PRODUCTIVITY',
    direction: 'down',
    targetValue: 1200,
    responsibleRole: 'WAREHOUSE_MANAGER',
    chartType: 'bar',
    displayOrder: 1,
  },
  {
    code: 'NOR_DIS_IND_11',
    categoryCode: 'CAT_3_3',
    name: 'Costo por unidad despachada',
    description: 'Costo promedio por unidad despachada.',
    formula: 'Costos de despacho / Unidades despachadas',
    unit: 'COP',
    unitType: 'currency',
    indicatorClass: 'PRODUCTIVITY',
    direction: 'down',
    targetValue: 800,
    responsibleRole: 'WAREHOUSE_MANAGER',
    chartType: 'bar',
    displayOrder: 2,
  },
  {
    code: 'NOR_DIS_IND_12',
    categoryCode: 'CAT_3_3',
    name: 'Unidades despachadas por empleado',
    description: 'Productividad del personal de despacho.',
    formula: 'Unidades despachadas / Número de empleados de despacho',
    unit: 'und/emp',
    unitType: 'units',
    indicatorClass: 'PRODUCTIVITY',
    direction: 'up',
    targetValue: 450,
    responsibleRole: 'WAREHOUSE_MANAGER',
    chartType: 'line',
    displayOrder: 3,
  },
  {
    code: 'NOR_DIS_IND_13',
    categoryCode: 'CAT_3_3',
    name: 'Costo por metro cuadrado',
    description: 'Costo de almacenamiento por área.',
    formula: 'Costos de almacén / Metros cuadrados utilizados',
    unit: 'COP/m²',
    unitType: 'currency',
    indicatorClass: 'PRODUCTIVITY',
    direction: 'down',
    targetValue: 15000,
    responsibleRole: 'WAREHOUSE_MANAGER',
    chartType: 'bar',
    displayOrder: 4,
  },
  {
    code: 'NOR_DIS_IND_14',
    categoryCode: 'CAT_3_3',
    name: 'Costo de despachos por empleado',
    description: 'Costo laboral de despacho por empleado.',
    formula: 'Costos de despacho / Número de empleados',
    unit: 'COP',
    unitType: 'currency',
    indicatorClass: 'PRODUCTIVITY',
    direction: 'down',
    targetValue: 2500000,
    responsibleRole: 'WAREHOUSE_MANAGER',
    chartType: 'bar',
    displayOrder: 5,
  },
  {
    code: 'NOR_DIS_IND_15',
    categoryCode: 'CAT_3_3',
    name: 'Nivel de cumplimiento en despachos',
    description: 'Despachos completados a tiempo y sin error.',
    formula: '(Despachos cumplidos / Total despachos programados) × 100',
    unit: '%',
    unitType: 'percentage',
    indicatorClass: 'PERFORMANCE',
    direction: 'up',
    targetValue: 96,
    responsibleRole: 'WAREHOUSE_MANAGER',
    chartType: 'line',
    displayOrder: 6,
  },
  // 3.4 Transporte
  {
    code: 'NOR_DIS_IND_16',
    categoryCode: 'CAT_3_4',
    name: 'Costo de transporte vs ventas',
    description: 'Participación del transporte en las ventas.',
    formula: '(Costo total transporte / Ventas netas) × 100',
    unit: '%',
    unitType: 'percentage',
    indicatorClass: 'PRODUCTIVITY',
    direction: 'down',
    targetValue: 8,
    responsibleRole: 'TRANSPORT_MANAGER',
    chartType: 'line',
    displayOrder: 1,
  },
  {
    code: 'NOR_DIS_IND_17',
    categoryCode: 'CAT_3_4',
    name: 'Costo operativo por conductor',
    description: 'Costo promedio por conductor en el periodo.',
    formula: 'Costos operativos de transporte / Número de conductores',
    unit: 'COP',
    unitType: 'currency',
    indicatorClass: 'PRODUCTIVITY',
    direction: 'down',
    targetValue: 8500000,
    responsibleRole: 'TRANSPORT_MANAGER',
    chartType: 'bar',
    displayOrder: 2,
  },
  {
    code: 'NOR_DIS_IND_18',
    categoryCode: 'CAT_3_4',
    name: 'Comparativo de transporte',
    description: 'Comparación de costos entre modos o rutas de transporte.',
    formula: 'Costo modo A vs Costo modo B (índice relativo)',
    unit: 'índice',
    unitType: 'ratio',
    indicatorClass: 'PERFORMANCE',
    direction: 'down',
    targetValue: 1,
    responsibleRole: 'TRANSPORT_MANAGER',
    chartType: 'composed',
    displayOrder: 3,
  },
  // 3.5 Servicio al cliente
  {
    code: 'NOR_DIS_IND_19',
    categoryCode: 'CAT_3_5',
    name: 'Entregas perfectas',
    description: 'Entregas completas, a tiempo y sin daños.',
    formula: '(Entregas perfectas / Total entregas) × 100',
    unit: '%',
    unitType: 'percentage',
    indicatorClass: 'PERFORMANCE',
    direction: 'up',
    targetValue: 94,
    responsibleRole: 'GENERAL_MANAGER',
    chartType: 'line',
    displayOrder: 1,
  },
  {
    code: 'NOR_DIS_IND_20',
    categoryCode: 'CAT_3_5',
    name: 'Entregas a tiempo',
    description: 'Entregas dentro de la ventana comprometida.',
    formula: '(Entregas a tiempo / Total entregas) × 100',
    unit: '%',
    unitType: 'percentage',
    indicatorClass: 'PERFORMANCE',
    direction: 'up',
    targetValue: 95,
    responsibleRole: 'GENERAL_MANAGER',
    chartType: 'line',
    displayOrder: 2,
  },
  {
    code: 'NOR_DIS_IND_21',
    categoryCode: 'CAT_3_5',
    name: 'Pedidos completos',
    description: 'Pedidos entregados sin faltantes.',
    formula: '(Pedidos completos / Total pedidos) × 100',
    unit: '%',
    unitType: 'percentage',
    indicatorClass: 'PERFORMANCE',
    direction: 'up',
    targetValue: 97,
    responsibleRole: 'GENERAL_MANAGER',
    chartType: 'line',
    displayOrder: 3,
  },
  {
    code: 'NOR_DIS_IND_22',
    categoryCode: 'CAT_3_5',
    name: 'Documentación sin problemas',
    description: 'Entregas con documentación correcta.',
    formula: '(Entregas sin novedad documental / Total entregas) × 100',
    unit: '%',
    unitType: 'percentage',
    indicatorClass: 'PERFORMANCE',
    direction: 'up',
    targetValue: 99,
    responsibleRole: 'GENERAL_MANAGER',
    chartType: 'bar',
    displayOrder: 4,
  },
  {
    code: 'NOR_DIS_IND_23',
    categoryCode: 'CAT_3_5',
    name: 'Costos logísticos vs ventas',
    description: 'Peso de la logística sobre ventas.',
    formula: '(Costos logísticos totales / Ventas netas) × 100',
    unit: '%',
    unitType: 'percentage',
    indicatorClass: 'PRODUCTIVITY',
    direction: 'down',
    targetValue: 12,
    responsibleRole: 'GENERAL_MANAGER',
    chartType: 'line',
    displayOrder: 5,
  },
  {
    code: 'NOR_DIS_IND_24',
    categoryCode: 'CAT_3_5',
    name: 'Costos logísticos vs utilidad bruta',
    description: 'Relación costos logísticos y utilidad bruta.',
    formula: '(Costos logísticos / Utilidad bruta) × 100',
    unit: '%',
    unitType: 'percentage',
    indicatorClass: 'PRODUCTIVITY',
    direction: 'down',
    targetValue: 25,
    responsibleRole: 'GENERAL_MANAGER',
    chartType: 'line',
    displayOrder: 6,
  },
  {
    code: 'NOR_DIS_IND_25',
    categoryCode: 'CAT_3_5',
    name: 'Costo CEDI vs ventas',
    description: 'Costo del centro de distribución sobre ventas.',
    formula: '(Costos CEDI / Ventas netas) × 100',
    unit: '%',
    unitType: 'percentage',
    indicatorClass: 'PRODUCTIVITY',
    direction: 'down',
    targetValue: 5,
    responsibleRole: 'GENERAL_MANAGER',
    chartType: 'line',
    displayOrder: 7,
  },
  // 3.6 Importaciones
  {
    code: 'NOR_DIS_IND_28',
    categoryCode: 'CAT_3_6',
    name: 'Costo por unidad importada/exportada',
    description: 'Costo logístico unitario de comercio exterior.',
    formula: 'Costos logísticos internacionales / Unidades importadas o exportadas',
    unit: 'COP',
    unitType: 'currency',
    indicatorClass: 'PRODUCTIVITY',
    direction: 'down',
    targetValue: 45000,
    responsibleRole: 'GENERAL_MANAGER',
    chartType: 'bar',
    displayOrder: 1,
  },
];

/** KPIs con serie histórica demo de 12 meses (uno por categoría principal) */
export const DEMO_TIME_SERIES_KPIS = [
  'NOR_DIS_IND_04',
  'NOR_DIS_IND_09',
  'NOR_DIS_IND_15',
  'NOR_DIS_IND_19',
] as const;

/** Valores base para generar series demo */
export const DEMO_BASE_VALUES: Record<string, { base: number; target: number; variance: number }> = {
  NOR_DIS_IND_04: { base: 92, target: 95, variance: 2.5 },
  NOR_DIS_IND_09: { base: 96.5, target: 98, variance: 1.2 },
  NOR_DIS_IND_15: { base: 93, target: 96, variance: 2 },
  NOR_DIS_IND_19: { base: 91, target: 94, variance: 2.5 },
};
